/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import DAO.chiTietPhieuNhapDao;
import DAO.sanPhamDao;
import POJO.chiTietPhieuNhapPojo;
import POJO.sanPhamPojo;
import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Paragraph;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.BaseFont;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfTable;
import com.lowagie.text.pdf.PdfWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import table.TableCustom;

/**
 *
 * @author AnhDoan
 */
public class frmChiTietPN extends javax.swing.JFrame {

    /**
     * Creates new form frmChiTietPN
     */
    DecimalFormat formatter = new DecimalFormat("###,###,###");
    public frmChiTietPN() {
        initComponents();
        tableCustom1.apply(jScrollPane1, TableCustom.TableType.DEFAULT);
        loadCTPN();
        tbCTPN.setDefaultEditor(Object.class, null);
    }
    
     public void loadCTPN() {
        try {
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new String[]{"Tên sản phẩm","Màu sắc","Kích cỡ", "Số lượng nhập", "Giá nhập"});
            chiTietPhieuNhapDao ctpnDAO = new chiTietPhieuNhapDao();
            ArrayList<chiTietPhieuNhapPojo> dsCTPN = ctpnDAO.layDSCTPN(frmNhanVienKho.maPN);
            for (chiTietPhieuNhapPojo ct : dsCTPN) {
                String tenSP = ct.getTensp();
                String mau = ct.getMauSac();
                String kt = ct.getKichThuoc();
                String giaNhap = ct.getGianhap();
                String soLuong = ct.getSoluong();
                model.addRow(new Object[]{tenSP,mau,kt, soLuong, formatter.format(Double.parseDouble(giaNhap)) + " VNĐ"});
            }

            tbCTPN.setModel(model);
            lbMPN.setText(frmNhanVienKho.maPN);
            lbNCC.setText(frmNhanVienKho.nhaCungCap);
            lbNV.setText(frmNhanVienKho.nhanVienLap);
            lbTG.setText(frmNhanVienKho.ngayLap);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCustom1 = new table.TableCustom();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tableScrollButton1 = new table.TableScrollButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCTPN = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbMPN = new javax.swing.JLabel();
        lbNV = new javax.swing.JLabel();
        lbNCC = new javax.swing.JLabel();
        lbTG = new javax.swing.JLabel();
        button1 = new sample.message.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(22, 122, 197));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHI TIẾT PHIẾU NHẬP");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        tbCTPN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbCTPN);

        tableScrollButton1.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Mã phiếu nhập:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nhân viên lập:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nhà cung cấp:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Thời gian lập:");

        lbMPN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbMPN.setText("jLabel6");

        lbNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNV.setText("jLabel7");

        lbNCC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNCC.setText("jLabel8");

        lbTG.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbTG.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMPN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNV, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbNCC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbTG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lbMPN)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(lbNCC)))
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(lbNV)
                    .addComponent(lbTG))
                .addGap(47, 47, 47)
                .addComponent(tableScrollButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        button1.setBackground(new java.awt.Color(0, 102, 51));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-print-25.png"))); // NOI18N
        button1.setText("Xuất phiếu");
        button1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        button1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button1MouseClicked(evt);
            }
        });
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void button1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button1MouseClicked
        String url = "";
        JFileChooser j = new JFileChooser();
        j.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int x = j.showSaveDialog(this);
        if (x == JFileChooser.APPROVE_OPTION) {
            url = j.getSelectedFile().getPath() + File.separator;
        }

        String fileName = "phieunhap.pdf";
        File file = new File(url + fileName);

        int counter = 1;
        while (file.exists()) {
            fileName = "phieunhap(" + counter + ").pdf";
            file = new File(url + fileName);
            counter++;
        }

        Document doc = new Document();
        try {
            PdfWriter.getInstance(doc, new FileOutputStream(file));
            doc.open();

            BaseFont bf = BaseFont.createFont("Roboto/Roboto-Regular.ttf", BaseFont.IDENTITY_H, BaseFont.EMBEDDED);
            Font font = new Font(bf, 12);
            Font titleFont = new Font(bf, 18, Font.BOLD); 
           
            PdfPTable headerTable1 = new PdfPTable(1);
            headerTable1.setWidthPercentage(100);
            headerTable1.setSpacingAfter(15);

            PdfPCell cellTT1 = new PdfPCell(new Phrase("Công ty TNHH Thời Trang và Mỹ Phẩm Châu Âu", font));
            cellTT1.setBorder(Rectangle.NO_BORDER);
            PdfPCell cellTT2 = new PdfPCell(new Phrase("Địa chỉ: Lầu 12, Toà Nhà Sonatus, 15 Lê Thánh Tôn, Phường Bến Nghé, Quận 1, TP.HCM", font));
            cellTT2.setBorder(Rectangle.NO_BORDER);
            PdfPCell cellTT3 = new PdfPCell(new Phrase("Điện thoại: +84(28) 3825 6523", font));
            cellTT3.setBorder(Rectangle.NO_BORDER);

            headerTable1.addCell(cellTT1);
            headerTable1.addCell(cellTT2);
            headerTable1.addCell(cellTT3);
            doc.add(headerTable1);
            
            Paragraph title = new Paragraph("PHIẾU NHẬP", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            title.setSpacingAfter(20);
            doc.add(title);

            PdfPTable headerTable = new PdfPTable(2);
            headerTable.setWidthPercentage(100);
            headerTable.setSpacingAfter(10);

            headerTable.setWidths(new float[]{1, 1});

            PdfPCell cell1 = new PdfPCell(new Phrase("Mã phiếu nhập: " + lbMPN.getText(), font));
            cell1.setBorder(Rectangle.NO_BORDER);
            PdfPCell cell2 = new PdfPCell(new Phrase("Nhà cung cấp: " + lbNCC.getText(), font));
            cell2.setBorder(Rectangle.NO_BORDER);

            PdfPCell cell3 = new PdfPCell(new Phrase("Nhân viên lập: " + lbNV.getText(), font));
            cell3.setBorder(Rectangle.NO_BORDER);
            PdfPCell cell4 = new PdfPCell(new Phrase("Thời gian lập: " + lbTG.getText(), font));
            cell4.setBorder(Rectangle.NO_BORDER);

            headerTable.addCell(cell1);
            headerTable.addCell(cell2);
            headerTable.addCell(cell3);
            headerTable.addCell(cell4);

            doc.add(headerTable);

            PdfPTable tbl = new PdfPTable(7);
            tbl.setWidthPercentage(100);
            tbl.setWidths(new float[]{0.5f, 2f, 1.2f, 1.2f, 1.8f, 1.5f, 2f});
            
            PdfPCell header1 = new PdfPCell(new Phrase("STT", font));
            header1.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell header2 = new PdfPCell(new Phrase("Tên sản phẩm", font));
            header2.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell header3 = new PdfPCell(new Phrase("Màu sắc", font));
            header3.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell header4 = new PdfPCell(new Phrase("Kích cỡ", font));
            header4.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell header5 = new PdfPCell(new Phrase("Số lượng nhập", font));
            header5.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell header6 = new PdfPCell(new Phrase("Giá nhập", font));
            header6.setHorizontalAlignment(Element.ALIGN_CENTER);
            PdfPCell header7 = new PdfPCell(new Phrase("Thành tiền", font));
            header7.setHorizontalAlignment(Element.ALIGN_CENTER);
            tbl.addCell(header1);
            tbl.addCell(header2);
            tbl.addCell(header3);
            tbl.addCell(header4);
            tbl.addCell(header5);
            tbl.addCell(header6);
            tbl.addCell(header7);

            double tongTien = 0;
            int tongSLN = 0;
            int stt = 1;
            for (int i = 0; i < tbCTPN.getRowCount(); i++) {
                String tenSanPham = tbCTPN.getValueAt(i, 0).toString();
                String mau = tbCTPN.getValueAt(i, 1).toString();
                String kt = tbCTPN.getValueAt(i, 2).toString();
                String soLuongNhap = tbCTPN.getValueAt(i, 3).toString();
                String giaNhap = tbCTPN.getValueAt(i, 4).toString();
                String giaNhapClean = giaNhap.replaceAll("[^\\d]", "");

                double giaNhapDouble = Double.parseDouble(giaNhapClean);

                tongTien += giaNhapDouble * Integer.parseInt(soLuongNhap);
                tongSLN += Integer.parseInt(soLuongNhap);
                double thanhTien = giaNhapDouble * Integer.parseInt(soLuongNhap);
               
                
                PdfPCell cellSTT = new PdfPCell(new Phrase(String.valueOf(stt), font));
                cellSTT.setHorizontalAlignment(Element.ALIGN_CENTER);
                tbl.addCell(cellSTT);
                
                PdfPCell cellTenSP = new PdfPCell(new Phrase(tenSanPham, font));
                cellTenSP.setHorizontalAlignment(Element.ALIGN_CENTER);
                tbl.addCell(cellTenSP);
                
                PdfPCell cellMauSac = new PdfPCell(new Phrase(mau, font));
                cellMauSac.setHorizontalAlignment(Element.ALIGN_CENTER);
                tbl.addCell(cellMauSac);
                
                PdfPCell cellKT= new PdfPCell(new Phrase(kt, font));
                cellKT.setHorizontalAlignment(Element.ALIGN_CENTER);
                tbl.addCell(cellKT);
                
                PdfPCell cellSLN = new PdfPCell(new Phrase(soLuongNhap, font));
                cellSLN.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tbl.addCell(cellSLN);
                
                PdfPCell cellGiaNhap = new PdfPCell(new Phrase(giaNhap, font));
                cellGiaNhap.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tbl.addCell(cellGiaNhap);
                
                PdfPCell cellThanhTien = new PdfPCell(new Phrase(formatter.format(thanhTien) + " VNĐ", font));
                cellThanhTien.setHorizontalAlignment(Element.ALIGN_RIGHT);
                tbl.addCell(cellThanhTien);
                stt++;
            }

            doc.add(tbl);
            
            PdfPTable bottomTable = new PdfPTable(2);
            bottomTable.setWidthPercentage(100);
            bottomTable.setSpacingBefore(20);

            bottomTable.setWidths(new float[]{1.9f, 1});

            PdfPCell cellTSL = new PdfPCell(new Phrase("Tổng số lượng nhập: " + tongSLN , font));
            cellTSL.setHorizontalAlignment(Element.ALIGN_RIGHT);
            cellTSL.setBorder(Rectangle.NO_BORDER);
            PdfPCell cellTT = new PdfPCell(new Phrase("Tổng tiền: " + formatter.format(tongTien) + " VNĐ" , font));
            cellTT.setHorizontalAlignment(Element.ALIGN_RIGHT);
            cellTT.setBorder(Rectangle.NO_BORDER);

            bottomTable.addCell(cellTSL);
            bottomTable.addCell(cellTT);

            doc.add(bottomTable);
            
            JOptionPane.showMessageDialog(rootPane, "Xuất phiếu nhập thành công !");
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            doc.close();
        }

    }//GEN-LAST:event_button1MouseClicked

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmChiTietPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmChiTietPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmChiTietPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmChiTietPN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmChiTietPN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sample.message.Button button1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbMPN;
    private javax.swing.JLabel lbNCC;
    private javax.swing.JLabel lbNV;
    private javax.swing.JLabel lbTG;
    private table.TableCustom tableCustom1;
    private table.TableScrollButton tableScrollButton1;
    private javax.swing.JTable tbCTPN;
    // End of variables declaration//GEN-END:variables
}
